Tag component
wwnorton/design-system pull request #153
Opened 2021-05-25 18:35 UTC by Apatil15

- adds Tag component
- adds Tag scss styling and tokens
- adds color prop based on SystemColors and RoleColors

2021-05-30 21:58 UTC, sh0ji reviewed
I'm keeping my review for this one light since a lot of it overlaps with `Badge` and we're still waiting on visual designs for this.

There are some things you can change, based on my Badge feedback, though. For instance, you need to pass the `ref` to the `span`, and most of the token/CSS comments apply here too.

2021-05-30 21:58 UTC, sh0ji commented on packages/core/src/components/tag/index.scss
> +@mixin tag-close-icon {
We need to figure out what this should be called. "Close icon" doesn't seem quite right for two reasons:

1. "close" implies it can be opened, which implies the existence of an `isOpen` prop, which we are not including.
2. This should be a button (it's clickable), not an icon.

With that in mind, I'm inclined to call it the "dismiss button" or even just "dismiss" since the corresponding prop is `dismissable`. Let's wait and see what the Zeplin board calls this before making a decision, though.

2021-05-30 21:58 UTC, sh0ji commented on packages/react/src/components/Tag/Tag.tsx
> +				<Icon
This should be a `<Button icon="close" iconOnly>Dismiss</Button>`. In general, if you're attaching an `onClick` callback, it should probably be a button or another interactive element like a `<summary>` or `<div role="menuitem" tabindex="0">` (an interactive `role` and `tabindex` can make otherwise non-interactive elements interactive).

2021-07-06 18:04 UTC, Apatil15 commented
Change aș per the design

By default button
Dismissable entire tag close
Added test cases

2021-07-12 18:42 UTC, Apatil15 commented
Change aș per the design 
1. By default button 
2. When dismissible and click anywhere in the tag getting close
3. When added link tag convert into span
4. Added test cases

@sh0ji Please review it

2021-07-29 18:53 UTC, sh0ji requested changes
@Apatil15, i have a few change requests and one question about whether it'd be better to revisit using an `href` prop to render the tag with a link.

And there are a handful of things in the props interface that need tweaking. Here's what I'm thinking:

```tsx
export interface TagProps extends React.HTMLAttributes<HTMLElement> {
	/**
	 * When defined, the tag will render as a `Link`. Otherwise, the tag will
	 * render as a `Button`.
	*/
	href?: string;
	/** Indicates whether callout can be dismissed. */
	dismissible?: boolean;
	/** The callout's color family. */
	color?: Exclude<AllColors, 'disabled'>;
	/** Callback function that is called when the callout is dismissed. */
	onDismiss?: () => void;
	/** The base class name according to BEM conventions. */
	baseName?: string,
	/** The className that will be applied to the dismiss icon. */
	dismissIconClass?: string,
}
```

2021-07-29 18:53 UTC, sh0ji commented on packages/react/src/components/Tag/types.ts
> +	icon?: IconProps['variant'],
Like Badge, I'm inclined to remove this prop entirely since it adds complexity without a ton of benefit. The difference between the following isn't a significant amount of work and the latter makes it easier to understand what will render.

```jsx
<Tag icon="account">Account</Tag>

<Tag>
  <Icon variant="account" />
  Account
</Tag>
```

2021-07-29 18:53 UTC, sh0ji commented on packages/react/src/components/Tag/types.ts
> +	link?: boolean;
This can be removed.

2021-08-03 16:56 UTC, Apatil15 commented on packages/react/src/components/Tag/Tag.tsx
> +	let isLink = false;
I have added following conditions to validate link elements only, I verified with above all examples.

`if (children && React.isValidElement(children)) {
			if(children.type === "a"){
				return true;
			}else if(children.props && children.props.href){
				return true;
			}
		}
		return false;`

Exception only is fragment element with anchor or link
`<Tag>
  <>
    <a>An anchor</a>
  </>
</Tag>`

2021-08-03 19:46 UTC, Apatil15 commented on packages/react/src/components/Tag/types.ts
> +	link?: boolean;
@sh0ji As per the suggestions I have made the changes and pushed

2021-08-05 23:30 UTC, sh0ji commented on packages/react/src/components/Tag/Tag.tsx
> +	let isLink = false;
Yeah, I like this idea!

For the fragment case, you could test for a fragment with [react-is#isFragment](https://github.com/facebook/react/tree/main/packages/react-is#fragment) (we're already using this dependency). This would mean that you'd need to make this a callback so you can use it recursively:

```jsx
import ReactIs from 'react-is';

export const isLinkElement = (node: React.ReactNode): boolean => {
	if (ReactIs.isElement(node) && (node.type === 'a' || typeof node.props.href === 'string')) {
		return true;
	}
	if (ReactIs.isFragment(node)) return isLinkElement(node.props.children);
	return false;
};
```

(I also simplified the first conditional here a bit and more strictly tested the `href`)

What do you think about exporting this link from [our link utility](https://github.com/wwnorton/design-system/tree/main/packages/react/src/utilities/link) so we can use it elsewhere if we ever need to find out if a child is a link? This doesn't make sense as a hook, so you'll have to create a new file in that utility directory since this is just a function (perhaps `functions.tsx`).

2021-08-10 18:12 UTC, Apatil15 commented on packages/react/src/components/Tag/Tag.tsx
> +	let isLink = false;
@sh0ji Made the changes as per the suggestion and pushed it

2021-08-10 21:42 UTC, sh0ji requested changes
Nice, we're very close! I was quite thorough, but the two big change requests are related to lifting the render state out of the `Tag` and moving the files around a bit.

2021-08-10 21:42 UTC, sh0ji commented on packages/react/src/components/Tag/Tag.tsx
> +			[`${baseName}__dismissible`]: dismissible === true,
This should be `--dismissible`. "Dismissible" is a [modifier](https://www.freecodecamp.org/news/a-quick-introduction-to-block-element-modifiers-bem-9df46d29b64c/), not an element.

2021-08-10 21:42 UTC, sh0ji commented on packages/react/src/components/Tag/Tag.tsx
> +	closeIconClass = `${baseName}__dismissible__icon`,
This should be `__dismiss-icon`. In BEM, the `__` syntax means that the thing on the right belongs to the anatomy of the thing on the left, so what you have implies that "icon" is part of the anatomy of "dismissible," which is part of the anatomy of "nds-tag." More accurately, this is a dismiss icon that belongs to the tag.

2021-08-10 21:42 UTC, sh0ji commented on packages/react/src/components/Tag/types.ts
> +	dismissClass?: string,
This doesn't appear to be used for anything and seems to describe the same thing as `closeIconClass`. I think I like `dismissClass` more than `closeIconClass`, though&mdash;it's simpler. What do you think?

2021-08-10 21:42 UTC, sh0ji commented on packages/react/src/components/Tag/index.stories.tsx
> +		<Tag color="blue" style={{ marginRight: 4 }}>
A little tip: instead of setting the margin of the items, use the [gap property](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) on the container (flex or grid).

```jsx
export const MultipleTags: React.FunctionComponent = () => (
	<div style={{ display: 'flex', gap: 4 }}>
		<Tag color="blue">
			Default Tag
		</Tag>
		<Tag color="green">
			<Icon variant="download" />
			With Icon
		</Tag>
		<Tag dismissible color="red">
			Dismissible
		</Tag>
	</div>
);
```

2021-08-10 21:42 UTC, sh0ji commented on packages/core/src/components/tag/index.scss
> +		.nds-tag__icon {
I don't think this is implemented anywhere, is it? It's up to the developer to set the `<Icon>`.

2021-08-11 02:24 UTC, Apatil15 commented on packages/react/src/utilities/functions.ts
> +	const isLink = (childNode: ReactNode):boolean => {
I was trying to add useMemo in this function, Now removed

2021-08-11 02:25 UTC, Apatil15 commented on packages/react/src/utilities/index.ts
> +export * from './functions';
Moved inside link folder

2021-08-11 02:26 UTC, Apatil15 commented on packages/react/src/utilities/functions.ts
> +): boolean => {
Added following parameter
React.ReactNode | React.ReactElement<LinkLikeProps>

2021-08-11 02:26 UTC, Apatil15 commented on packages/react/src/utilities/functions.ts
> + * @param node
Removed

2021-08-11 02:26 UTC, Apatil15 commented on packages/react/src/components/Tag/Tag.tsx
> +					<Button
Changed to icon

2021-08-11 02:26 UTC, Apatil15 commented on packages/react/src/components/Tag/Tag.tsx
> +			{ isLinkElement(children) ? LinkTag : DefaultTag }
Done

2021-08-11 02:27 UTC, Apatil15 commented on packages/react/src/components/Tag/Tag.tsx
> +			setDismissed(true);
Made changes as per suggestions

2021-08-11 02:28 UTC, Apatil15 commented on packages/core/src/components/tag/index.scss
> +	a,
Removed from the base class and added in mixing

2021-08-11 02:28 UTC, Apatil15 commented on packages/react/src/components/Tag/Tag.tsx
> +			[`${baseName}__dismissible`]: dismissible === true,
Done

2021-08-11 02:50 UTC, Apatil15 commented on packages/core/src/components/tag/index.scss
> +		.nds-tag__icon {
@sh0ji Made the changes as per the review suggestions

2021-08-16 01:22 UTC, sh0ji commented on packages/react/src/components/Tag/Tag.tsx
> +	closeIconClass = `${baseName}__dismissible__icon`,
After reviewing the AC, I realized that the dismiss icon _is_ supposed to be a button so I changed this back to just `dismissClass` and set it as a button.

> If the component has a dismiss button...clicking the dismiss button causes the component to disappear. 

2021-08-16 01:22 UTC, sh0ji commented on packages/react/src/components/Tag/Tag.tsx
> +					<Button
See https://github.com/wwnorton/design-system/pull/153#discussion_r689185670

2021-08-16 01:30 UTC, sh0ji commented on packages/react/src/utilities/functions.ts
> +): boolean => {
Check 0232a87 to see what I meant. And please ask questions in the code review if you're ever not sure.

2021-08-16 01:31 UTC, sh0ji commented on packages/react/src/components/Tag/types.ts
> +	dismissClass?: string,
Went with `dismissClass`.

2021-08-16 02:27 UTC, merged