Badge component
wwnorton/design-system pull request #154
Opened 2021-05-25 23:49 UTC by Apatil15

adds Badge component
adds Badge scss styling and tokens
adds color prop based on SystemColors

2021-05-30 21:31 UTC, sh0ji requested changes
I was very thorough but this looks great in general. Thanks for opening it!

My change requests are primarily focused on two things:

1. Tokens/CSS to ensure that we're exposing the right things to make it themeable.
2. Removing the `variant` prop since there are only really 2 "variants" and one of them should be the default ("pill").

2021-05-30 21:31 UTC, sh0ji commented on packages/core/src/components/badge/tokens.scss
> +$padding-pill: spacing.spacer('cell-sm') !default;
Based on my comments above, I think this file should look like this:

```scss
$padding-x: spacing.spacer('0.5rem') !default;
$padding-y: {some_calculated_default} !default;
$background-family: 'base-color' !default;
$background-grade: 70 !default;
$font-size: var(--nds-font-size-sm) !default;

$dot-color: var(--nds-red-50) !default;
$dot-size: spacing.spacer('0.5rem') !default;
```

2021-05-30 21:31 UTC, sh0ji commented on packages/core/src/components/badge/index.scss
> +	border-radius: var(--nds-badge-border-radius);
I think this can be hard-coded as `var(--nds-radius-pill)` rather than using a component token since it should use the "pill" radius by definition (it's not customizable).

2021-05-30 21:31 UTC, sh0ji commented on packages/core/src/index.scss
> +	@include nds.badge-style;
Please sort this list of includes alphabetically for better readability.

2021-05-30 21:31 UTC, sh0ji commented on packages/react/src/components/Badge/types.ts
> +	variant?: 'pill' | 'dot',
How do you feel about simplifying this to a `dot` boolean prop to simplify the API?

```html
// this should render the "pill" variant
<Badge>9</Badge>

// this should ignore children and render the "dot" variant
<Badge dot>9</Badge>
```

2021-05-30 21:31 UTC, sh0ji commented on packages/react/src/components/Badge/types.ts
> +	icon?: IconProps['variant'],
The main icon exports the `IconVariant` type, which you can import and use directly instead of referencing the prop.

2021-05-30 21:31 UTC, sh0ji commented on packages/react/src/components/Badge/types.ts
> +	closeIconClass?: string;
This is unused and can be removed.

2021-05-30 21:31 UTC, sh0ji commented on packages/react/src/components/Badge/index.stories.tsx
> +		<Badge color="red" variant="dot" />
Rather than displaying both in one story, just write a separate story for each (or use a knob to control it). Assuming you switch to the `dot` prop instead of the `variant`:

```tsx
export const Default: React.FunctionComponent = () => <Badge>9</Badge>;
export const Dot: React.FunctionComponent = () => <Badge dot>9</Badge>;
```

2021-05-30 21:31 UTC, sh0ji commented on packages/react/src/components/Badge/Badge.tsx
> +			? { ...baseProps, variant: icon, size: 12 }
`size` should be a relative value so the icon scales with the font size.

2021-05-30 21:31 UTC, sh0ji commented on packages/react/src/components/Badge/Badge.tsx
> +}: BadgeProps) => {
You've omitted the second parameter of the forwardRef callback (the `ref`). You need to bind it to the element it's referencing.

```tsx
React.forwardRef<HTMLSpanElement, Props>((props, ref) => <span {...props} ref={ref} />);
```

2021-06-07 15:36 UTC, Apatil15 commented
@sh0ji I have made changes as per the reviewed suggestions. Please verify

2021-06-07 19:17 UTC, sh0ji requested changes
This is coming along but there were a few items from the previous review that you didn't address. Please make sure to respond to my questions or add your comments in the conversation threads.

2021-06-07 19:17 UTC, sh0ji commented on packages/react/src/components/Badge/Badge.tsx
>  			{VariantProps}
Memoizing this adds more overhead than is gained. `{ (dot) ? null : children }` would accomplish the same thing without the overhead.

2021-06-07 19:17 UTC, sh0ji commented on packages/react/src/components/Badge/index.stories.tsx
>  export const Default: React.FunctionComponent = () => (
Let's make `dot` a knob in the stories rather than rendering both the default (pill) and dot in the same story. This also means stories can focus on demoing how to use things rather than the different permutations.

```tsx
export const Default: React.FunctionComponent = () => (
	<Badge
		dot={boolean('Dot', false)}
		icon={select('Icon', { None: undefined, ...IconOptions }, undefined)}
		color={select('Color', { None: undefined, ...SystemColorOptions }, undefined)}
	>
		{ text('Content', '11') }
	</Badge>
);
```

You can then remove the `WithIcon` story but still keep the `WithPopper` one, which I do think is helpful.

2021-06-07 19:17 UTC, sh0ji commented on packages/react/src/components/Badge/types.ts
> +	icon?: IconProps['variant'],
This can still be addressed.

2021-06-07 19:17 UTC, sh0ji commented on packages/core/src/components/badge/index.scss
> +	border-radius: var(--nds-badge-border-radius);
This is still applicable.

2021-06-07 19:17 UTC, sh0ji commented on packages/core/src/components/badge/index.scss
> +	line-height: type.lh(1);
this should be our [UI line height](https://github.com/wwnorton/design-system/blob/36902268dea9c252e75838b22f92ddc31613b310/packages/core/src/type/index.scss#L60-L63) (`1.25`).

2021-06-09 01:31 UTC, Apatil15 commented
@sh0ji Made changes as per the code reviewed suggestions, please verify

2021-06-09 13:28 UTC, sh0ji commented
Could you please go through [my unresolved change requests](https://github.com/wwnorton/design-system/pull/154/files/1e4f0802edd9cfc3043640b75e1f760df80e0ecc) to either reply to the comments or mark them as resolved, and then [re-request my review](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) when you're done? That will make it easier for me to know what's changed.

2021-06-11 20:25 UTC, Apatil15 commented
@sh0ji I have removed icon props and changed code accordingly, Please review it

2021-06-14 22:05 UTC, sh0ji requested changes
Three small changes. We also still need an answer from UX about what the `dot`'s default accessible name should be, since you'll need to set it as an `aria-label` when `dot={true}` and `aria-label={undefined}`.

2021-06-18 19:14 UTC, sh0ji commented on packages/react/src/components/Badge/index.test.tsx
> +	t.truthy(screen.getByText('99'));
It looks like you'll need to use (get/query)[ByLabelText](https://testing-library.com/docs/queries/bylabeltext/) for the `<Badge dot>99</Badge>` fixture since it will be named with an `aria-label` rather than its `textContent`.

2021-06-18 23:21 UTC, Apatil15 commented on packages/react/src/components/Badge/index.test.tsx
> +	t.truthy(screen.getByText('99'));
I used following function to read aria-label
```
t.truthy(screen.getByLabelText('has notification'));
```

2021-07-27 21:59 UTC, sh0ji commented
@Apatil15, I'm just merging this now and noticed that you left off the `!default` flag for a few of the tokens that you changed so I fixed that. I'll merge once CI is green.

2021-07-27 22:04 UTC, merged