TextField Multiline Component [NDS-16]
wwnorton/design-system pull request #160
Opened 2021-06-25 18:20 UTC by wguevara-norton

2021-06-29 18:48 UTC, cafrias reviewed
I only found those 2 things to comment about, I'll leave those as comments instead of change requests, I'll let you decide on the importance of the comments. Ping me back if you need anything!

2021-06-29 18:48 UTC, cafrias commented on packages/react/src/components/BaseInput/index.tsx
> +		return multiline ? (
I see we are duplicating code here, with the props passed to different component types. Wouldn't it be better for it to be something like:

```
// ... code
const Component = multiline ? 'textarea' : 'input';

return (
  <Component
    ref={setInput}
    onInput={inputHandler}
    maxLength={maxLengthRestrictsInput ? maxLength : undefined}
    {...attributes}
  />
)
```

I'll leave it there to you

2021-06-29 18:48 UTC, cafrias commented on packages/react/src/components/TextField/index.tsx
> +					if (child.type === React.Fragment) {
Here we have an unnecessary nested `if` ... this is the same as:

```
if (React.isValidElement(child) && child.type === React.Fragment) {
  return createFieldAddons(child.props.children);
}
```

2021-07-01 17:37 UTC, sh0ji requested changes
Looking good! Thanks so much for all your work on this. I had a few formatting change requests that I noted, as well as some prop comment changes.

The only big ask is that you pull out the `HTMLTextAreaElement` implementation into a `BaseTextArea`. The changes you've made to `BaseInput` have unintended effects on `Checkbox`, for instance, which extends `BaseInput` but would never extend `HTMLTextAreaElement`. If it turns out that `BaseInput` and `BaseTextArea` have duplicated code, you could think about where that might need to live external to the two to DRY it up a bit.

2021-07-01 17:37 UTC, sh0ji commented on packages/react/src/components/BaseInput/types.ts
> +	 * attribute to render TextArea always
This needs to be more descriptive. For instance, "When set, the resulting edit box will allow multiple lines of input."

2021-07-01 17:37 UTC, sh0ji commented on packages/react/src/components/BaseInput/types.ts
> +	 * @default false
Please remove this. We don't use the JSDoc syntax like this because defaults aren't defined here, they're defined in the default parameters of the actual function. The tool we use that reads these comments doesn't pick it up either. It _does_ pick up the default from the function, though.

In other words, this is how we document defaults:

```tsx
interface MyProps {
  /** Describe the prop here. */
  foo: string;
}

export MyComponent: React.FC<MyProps> = ({
  foo = 'bar', /* define the defaults here */
}) => { /* ... */ };
```

2021-07-01 17:37 UTC, sh0ji commented on packages/react/src/components/BaseInput/types.ts
> +	 * If `true` increase the height of textarea automatically
When describing a boolean, I prefer "When set, ...". Since React usage doesn't require you to explicitly define props as `true`, this feels a little more natural and helps prevent novice developers from thinking you actually have to set the prop as `true`.

In other words, while the following two are equivalent, they can and should be described differently:

```jsx
/* "foo" is set on the component */
<MyComponent foo />

/* "foo" is `true` */
<MyComponent foo={true} />
```

2021-07-01 17:37 UTC, sh0ji commented on packages/react/src/components/TextField/index.tsx
> +	(
Same comment as above. Please reformat to make the diff easier to understand.

2021-07-01 17:37 UTC, sh0ji commented on packages/react/src/components/TextField/types.ts
> +	multiline?: boolean;
You don't need to add these here since you're extending `BaseInputProps`, which already define them.

In general, if the prop name, prop type, and prop description are identical to an inherited prop, you shouldn't redefine it. If you need to change any of those, you can redefine it.

2021-07-01 17:37 UTC, sh0ji commented on packages/react/src/components/BaseInput/index.tsx
> +HTMLInputElement | HTMLTextAreaElement,
`BaseInput` should only implement `HTMLInputElement`, not `HTMLTextAreaElement`. You should create a `BaseTextArea` for that.

I apologize for not making this more clear, but `Base` components should only ever implement one element&mdash;they shouldn't ever do conditional rendering. You can think of them as a thin wrapper around HTML elements where we can polyfill functionality or fix cross-browser inconsistencies. Higher-level functions should be hoisted to public components.

(I borrowed this convention from [Vue.js's style guide](https://vuejs.org/v2/style-guide/#Base-component-names-strongly-recommended), which we could revisit for a 2.0 release)

2021-07-01 17:41 UTC, sh0ji requested changes

2021-07-01 17:41 UTC, sh0ji commented on packages/react/src/components/TextField/types.ts
> +	rows?: number;
Just realized that this prop is already defined on the [HTMLTextAreaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement#properties) interface, so you shouldn't redefine it here. In general, don't redefine DOM interface attributes unless you're _actually_ redefining them in the code.

2021-07-29 19:24 UTC, sh0ji commented
@wguevara-norton, any update on this?

2021-08-02 13:53 UTC, sh0ji commented on packages/react/src/components/BaseInput/index.tsx
> +	(
Are you maybe using Prettier to format these files?

2021-08-12 14:31 UTC, Apatil15 approved these changes

2021-08-16 03:57 UTC, sh0ji approved these changes
Looks good! Thanks, @wguevara-norton!

I made a few small changes to the stories for consistency and refactored the conditional rendering a bit to prevent the props that were unique to `BaseTextAreaProps` from being rendered on the `BaseInput` and vice versa. Specifically, the console was complaining that `autoResize` does not exist on `<input>`.

2021-08-16 04:19 UTC, merged