fix: wrap disclosure's summary in div [NDS-93]
wwnorton/design-system pull request #187
Opened 2021-08-03 21:21 UTC by JRebella

Workaround based on https://github.com/philipwalton/flexbugs#flexbug-9 to allow `<summary>` element to be a flexbox in safari

Tested in Safari 14.1.1:
![image](https://user-images.githubusercontent.com/47323512/128086986-49738471-1175-4e78-96df-57db5964ebb3.png)

2021-08-04 16:43 UTC, wguevara-norton approved these changes
LGTM 🤓

2021-08-05 13:55 UTC, sh0ji requested changes
Thanks for the PR, @JRebella! I appreciate that you took some time to address this. I requested a change to ensure that this component stays accessible.

2021-08-05 13:55 UTC, sh0ji commented on packages/react/src/components/BaseSummary/index.tsx
> +		<div {...attributes}>
This is going to create an issue where [the Disclosure's `onClick` handler](https://github.com/wwnorton/design-system/blob/a65d198b7f7dcdacd9702221765e88291508f4b8/packages/react/src/components/Disclosure/index.tsx#L271) won't trigger on `summary` clicks anymore and `div` elements don't register keyboard clicks, meaning this would create a regression and make our Disclosure inaccessible.

I'd prefer to keep the `attributes` object on the `summary` element to avoid this and any other potential issues (all `BaseSummary` callbacks should be passed to the `summary` element, for instance), and just change the CSS to move the flex box to the first child div.

2021-08-05 14:51 UTC, JRebella commented on packages/react/src/components/BaseSummary/index.tsx
> +		<div {...attributes}>
Good catch! I took some time to think about the repercussions of moving attributes down but definitively missed that one

I see two ways of getting around this:

1. Move `{...attributes}` back to the `summary` and change all components making use of `BaseSummary` so that they apply flexbox to the first div instead of the main container (should only be used by the disclosure, but it would impact any other project using the `BaseSummary` component directly)
2. Move `{...attributes}` back to the `summary` as well but also extract `classname` from the `BaseSummary` props and apply it to the `div` instead, like so:
```
export const BaseSummary = React.forwardRef<HTMLElement, BaseSummaryProps>(({
	marker,
	markerPosition = 'left',
	children,
  className
	...attributes
}: BaseSummaryProps, ref) => (
	<summary ref={ref} {...attributes}>
		<div className={className}>
			{ markerPosition === 'left' && marker }
			{ children }
			{ markerPosition === 'right' && marker }
		</div>
	</summary>
));
```

What do you think @sh0ji ?

2021-08-05 17:22 UTC, sh0ji commented on packages/react/src/components/BaseSummary/index.tsx
> +		<div {...attributes}>
This is effectively a polyfill that we'll probably want to remove sometime in the future, so I'd prefer a solution that is easy to remove. Even hard-coding `style={ display: 'flex' }` would be fine with me, since it would keep this change to one file and ensure that `BaseSummary` works reliably, independent of Disclosure.

Would leaving the `summary` as `display: flex;` (https://github.com/wwnorton/design-system/blob/main/packages/core/src/components/disclosure/index.scss#L25) cause any issues?

2021-08-05 17:23 UTC, sh0ji commented on packages/react/src/components/BaseSummary/index.tsx
> +		<div {...attributes}>
Oh, and whatever the solution, could you add a comment above the `div` to call out that this is a Safari 14 fix? That'll make it more clear in the future when we've forgotten why we did this.

2021-08-09 16:16 UTC, JRebella commented on packages/react/src/components/BaseSummary/index.tsx
> +		<div {...attributes}>
@sh0ji reverted ...attributes back to summary and went for the simple style={...} fix. Had to also add `width: '100%'` otherwise the div would shrink in firefox

Verified that the disclosure is now catching keyboard events as expected

2021-08-09 16:37 UTC, sh0ji reviewed
Great, this is very simple. Looks like our spell checker doesn't like "sumamry" or "flexbox" in your comment, though. Change them to "summary" and "flex box" to make everything green and then I think we're good to go.

2021-08-10 12:55 UTC, sh0ji approved these changes
:ship:

2021-08-10 14:55 UTC, merged