Link documentation update NDS-79
wwnorton/design-system pull request #196
Opened 2021-08-26 20:35 UTC by erinoh

Added updates to existing Link documentation.

2021-09-10 17:26 UTC, sh0ji requested changes
Looks great, I really like all of your updates! I had two suggestions that we'll need to resolve before merging.

2021-09-10 17:26 UTC, sh0ji commented on website/docs/components/link.mdx
>  - A link allows the user to return to the previous location by pressing the browser's back button.
Links only allow users to navigate to the link's destination, not back. The browser allows the user to navigate back/forward through their history, but those functions aren't links. We could include something about how they're related, or remove this entirely if it's confusing.

2021-09-10 17:26 UTC, sh0ji commented on website/docs/components/link.mdx
> +- When linking to the same URL on different pages, the linked text should be the same.
This was confusing to me on first read, but I think I figured it out. Maybe, "Links to the same destination should use the same link text, even when the links are on different pages."

2021-09-15 21:35 UTC, sh0ji commented on website/docs/components/link.mdx
>  - A link allows the user to return to the previous location by pressing the browser's back button.
@erinoh, I changed this in 7dd348ba5cc7187d71b85656081491709745bb7f:

> A link should always affect the browser history. In other words, after a user clicks a link to navigate to a new location, they should be able to return by pressing the browser's back button.

2021-09-15 21:37 UTC, sh0ji commented on website/docs/components/link.mdx
> +- A link does not need to be repeated in the same page or section.
@erinoh, this is the line you pointed out on our call. It needs to be more clear and include some explanation so that readers can make a judgment about when repeated links are okay/not okay.

2021-09-30 19:15 UTC, erinoh commented on website/docs/components/link.mdx
> +- A link does not need to be repeated in the same page or section.
@sh0ji I clarified these points and moved one from Dos to Usage. Let me know if you want to discuss further.

2021-09-30 19:17 UTC, erinoh commented on website/docs/components/link.mdx
> +- A link does not need to be repeated in the same page or section.
@sh0ji Actually I'm not seeing the edits I just made? Not sure if you can...

2021-10-01 14:58 UTC, sh0ji commented on website/docs/components/link.mdx
> +- A link does not need to be repeated in the same page or section.
You're not seeing it here because this comment is about the old version. GitHub adds the subtle "Outdated" badge to the file to signify this:
![image](https://user-images.githubusercontent.com/7939037/135641948-ffc32ef7-b9b7-4ce4-99ed-4a5ff9ccdda6.png)

Your changes can be seen in either the commit that you made (it's below this thread in the feed), or by clicking the "Files changed" tab at the top of the UI.

2021-10-01 15:01 UTC, merged