refactor(nds-198): refactored dropdown removed base dropdown and base …
wwnorton/design-system pull request #242
Opened 2021-11-22 18:59 UTC by Apatil15

Refactored dropdown with following code chanages. 

1. Added papper js
2. Removed baseListbox and baseOption
3. Added Listbox and option
4. Removed unwanted code.

2021-12-08 17:47 UTC, sh0ji requested changes
This is what I was hoping to see for this, @Apatil15. Nice job.

I called out a few little things but appreciate the thought you put into it all. After looking closely at everything, I do think the styles could use some refactoring (including listbox styling) but we could probably just do that in a future update.

2021-12-08 17:47 UTC, sh0ji commented on packages/core/src/components/dropdown/index.scss
> +	border: unset !important;
Is there a way to accomplish this without `!important`?

2021-12-08 17:47 UTC, sh0ji commented on packages/react/src/components/Dropdown/index.tsx
> +	listboxClass = `nds-listbox ${baseName}__listbox`,
If you want to use the `.nds-listbox` styles on the `.nds-dropdown__listbox`, you should use the mixin in the stylesheet to merge the styles and override them. Something like:

```scss
@use '../listbox';

@mixin listbox {
  @include listbox.base;
  @include listbox.group;

  // overrides have to come after the includes
  --nds-listbox-border: unset;
  --nds-listbox-border-radius: unset;
}

...

.nds-dropdown__listbox {
  @include listbox;
}
```

The downside here is that the resulting stylesheet will have duplicated styles, which I don't love. The alternative would be to refactor the listbox styles to separate base styling from more specific use cases (for example, making the border properties default to unset).

2021-12-08 17:47 UTC, sh0ji commented on packages/core/src/components/dropdown/index.scss
> +	overflow-y: none;
`none` isn't a valid [overflow value](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#values).

2021-12-08 17:47 UTC, sh0ji commented on packages/react/src/components/Dropdown/types.ts
> +| 'reference'
`reference` isn't being used so let's just remove it. If someone needs access to the button, we can talk about adding it then.

2021-12-08 17:47 UTC, sh0ji commented on packages/react/src/components/Dropdown/types.ts
> +| 'transition'
`transition` should be passed down to the Popper and let's give it a default value of "fade" so it uses the opacity transition by default.

2021-12-12 20:00 UTC, Apatil15 commented on packages/react/src/components/Dropdown/index.tsx
> +				matchWidth={
I used transition='fade'  and match with button story was not working as expected I tried all possible scenarios this is one of the them which I forgot to removed.

2021-12-12 20:01 UTC, Apatil15 commented on packages/react/src/components/Dropdown/types.ts
> +| 'transition'
I used transition='fade' but removed due to  one of the story MatchButtonWidth not working as expected, option is showing and hiding before match button width, it should be work like production.

2021-12-12 20:14 UTC, Apatil15 commented on packages/react/src/components/Dropdown/index.tsx
> +	listboxClass = `nds-listbox ${baseName}__listbox`,
Done

2021-12-12 20:17 UTC, Apatil15 commented on packages/core/src/components/dropdown/index.scss
> +	border: unset !important;
After included following implement in class no need !important
`@include listbox.base;`
`@include listbox.group;`

2021-12-12 20:17 UTC, Apatil15 commented on packages/core/src/components/dropdown/index.scss
> +	overflow-y: none;
Done

2021-12-13 01:30 UTC, Apatil15 commented on packages/react/src/components/Dropdown/index.tsx
> +	modifiers = [
Done

2021-12-13 01:31 UTC, Apatil15 commented
@sh0ji 
Changes has been pushed, please review and confirm 

https://pr-242.d2xq18ppjtz6lz.amplifyapp.com/storybook/?path=/story/dropdown--default

2021-12-15 21:02 UTC, Apatil15 commented on packages/react/src/components/Dropdown/types.ts
> +| 'transition'
I have added timeout  to setTransition transition 'fade'.

```js
setTimeout(() => {
setTransition(transitionProp);
}, 500);
```

2021-12-17 21:07 UTC, merged