Revert dec0e7311d3b4dc5211203c55c1d1ba72e65a84c typeset updates
wwnorton/design-system pull request #256
Opened 2022-02-02 14:40 UTC by wguevara-norton

2022-02-02 14:47 UTC, JRebella commented on website/sidebars.js
> -		'guides/usable-writing-guidelines',
Is this change intended?

2022-02-02 14:54 UTC, JRebella approved these changes
Approved but check the comment on sidebars.js please

2022-02-02 16:21 UTC, sh0ji requested changes
This should only have changes to `packages/core/src/type/index.scss`. Just as website changes shouldn't change design system packages, package changes shouldn't change the website.

2022-02-03 16:35 UTC, wguevara-norton commented on website/src/scss/main.scss
> -h1,
Evan that change is not from this commit to be reverted

2022-02-04 14:26 UTC, sh0ji commented on website/src/scss/main.scss
> -h1,
That's fine but I still don't know what that code was trying to accomplish or why it was part of this. I wasn't necessarily asking you to change anything&mdash;I just wanted to understand the change.

2022-02-04 21:28 UTC, sh0ji reviewed
We didn't get to go over this today, but I was hoping to ask if this was going to cause the documentation spacing to regress. If our documentation expects bigger heading margins, that should probably be moved to [website/src/scss/main.scss](https://github.com/wwnorton/design-system/blob/main/website/src/scss/main.scss) to avoid this breaking anything.

2022-02-14 15:55 UTC, sh0ji approved these changes

2022-02-14 15:56 UTC, sh0ji commented
LGTM! Once I've merged this, can you merge `main` into `modal-broken-spacing` so that it can be properly tested before we merge #258?

2022-02-14 15:58 UTC, merged