NDS-279: Avoid closing when click is released inside to ouside the modal
wwnorton/design-system pull request #264
Opened 2022-03-10 14:30 UTC by wguevara-norton

2022-03-15 19:00 UTC, sh0ji commented
@wguevara-norton, what needs to be done to move this along?

2022-03-21 23:01 UTC, sh0ji requested changes
Unless I'm missing something, here's what this should be doing:

* Store state to keep track of whether a click started on the dialog or not. I'll call this `isClickingDialog`.
* Set to `true` when a click starts on the dialog: `<Dialog onPointerDown={/* set isClickingDialog to true */} />`
* On mount (or on open?), add an event listener to the document to set to `false` on [pointerup](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onpointerup): `document.addEventListener('pointerup', /* setIsClickingDialogFalse */)`
* Remove the document event listener on unmount: `document.removeEventListener('pointerup', /* setIsClickingDialogFalse */)`
* Check the state when the backdrop is clicked: `<Backdrop onClick={/* do nothing if isClickingDialog is true */ } />`

2022-04-05 14:54 UTC, sh0ji commented
@wguevara-norton, you need to address the unresolved conversations and rebase before I can merge this.

2022-04-05 15:32 UTC, wguevara-norton commented on packages/react/src/components/Modal/index.tsx
> +		this.initialTarget = event.target;
We don't track `initialTarget` anymore since this function was renamed and refactored, and it's called only when in the `BaseDialog` occurs a `pointerdown` event, and sets `isClickingDialog` state as `true`

2022-04-05 15:33 UTC, wguevara-norton commented on packages/react/src/components/Modal/index.tsx
> +		document.addEventListener('mouseup', this.handleOnMouseUp);
`pointerup` event listener is removed now, we don't use anymore `mousedown` and `mouseup` events

2022-04-05 15:35 UTC, wguevara-norton commented on packages/react/src/components/Modal/index.tsx
> +		if (target?.contains(this.dialog) && this.dialog?.contains(this.initialTarget as Element)) {
This not anymore, but this `!this.dialog?.contains(event.target as Element)`. This actually is needed to know when the click or pointer event is being called outside the `BaseDialog`

2022-04-05 18:44 UTC, sh0ji approved these changes
Thanks, Wilmer! :ship:

2022-04-05 18:46 UTC, merged