NDS-157 - Step indicator component
wwnorton/design-system pull request #266
Opened 2022-03-15 15:19 UTC by JRebella

First iteration of the Step Indicator component

- Step indicator scss and tokens
- Step indicator and Step React components
- Storybook stories: Default, with long labels, with hidden connectors

2022-03-15 17:00 UTC, sh0ji commented
Awesome, thanks for all your work on this, @JRebella! I haven't had a chance to do a code review yet but did notice some visual anomalies with how the current step's "halo" renders around the stop circle. The circle effectively isn't fully centered at different zoom levels.

100% zoom on Firefox - very slightly off-center to the bottom right:

![100% zoom](https://user-images.githubusercontent.com/7939037/158430520-05c36a20-99ae-4792-a398-cad8fa472298.png)

90% zoom on Firefox - quite off-center to the top left:

![90% zoom](https://user-images.githubusercontent.com/7939037/158430621-2083f92d-dcec-4985-9c78-87acb36f763a.png)

It's not clear to me what's causing this, but I do know this can happen when you render things in layers (two different elements). Any ideas?

2022-03-15 19:23 UTC, JRebella commented
> 

Hmm good catch. At first glance I'm suspicious of the `scale` transform I used to have the current step 10% bigger, I ended up using scale due to another issue setting the size of the check-icon. I'll see how the circle behaves if I scale it up using a calculated height/width instead

2022-03-16 15:18 UTC, JRebella commented
> 

@sh0ji I tested rendering a circle with an offset outline in multiple ways but every method resulted in deformation under zoom levels
![image](https://user-images.githubusercontent.com/47323512/158624431-0a1ff843-80d5-4987-87ef-8fe7b6d96490.png)

I tried, using outline and outline-offset, using 3 divs one inside the other with the middle div having the same color as the background, drawing a circle using `svg`

Here's the link to the sandbox https://codesandbox.io/s/romantic-river-elo56k?file=/src/App.js

2022-03-21 22:17 UTC, sh0ji reviewed
Great stuff! Most of my comments are super minor. The only one of any real significance is the one about the `connected` prop's default value.

2022-03-21 22:22 UTC, sh0ji commented
Oh, could you rebase this? That coverage failure is because of the non-deterministic test that I removed in #265.

2022-03-25 17:23 UTC, JRebella commented on packages/react/src/components/StepIndicator/index.stories.tsx
> +interface StepIndicatorControls extends StepIndicatorProps {
Hmm that's a good point. Having some sort of separator between the story controls and actual props would be ideal but looking at the docs I don't think it can be done

I think that the best we can do is play with the description column, right now you can tell which aren't props by looking at those that have an empty description but we would put some text on those to make it more clear maybe, any ideas?

![image](https://user-images.githubusercontent.com/47323512/160170638-b27d3f32-70eb-4151-906d-a088c0c8d16c.png)

2022-03-25 17:24 UTC, JRebella commented on packages/react/src/components/StepIndicator/index.stories.tsx
> +	connected: boolean,
If you were referring to just the `connected` property then yes, that shouldn't be there

2022-03-28 22:12 UTC, sh0ji commented on packages/react/src/components/StepIndicator/index.stories.tsx
> +interface StepIndicatorControls extends StepIndicatorProps {
Yeah, let's use the description field. We should probably just use a generic default that unambiguously signals that it's not a component prop. How about something like, "This is a Storybook-only prop, and is not part of this component's interface."?

2022-03-28 22:12 UTC, sh0ji commented on packages/react/src/components/StepIndicator/index.stories.tsx
> +	connected: boolean,
Yep, I just meant that line.

2022-03-29 16:55 UTC, JRebella commented on packages/react/src/components/StepIndicator/index.stories.tsx
> +interface StepIndicatorControls extends StepIndicatorProps {
Sounds good, got any ideas on how we could setup that string as a constant somewhere and distribute it to the stories?

2022-03-29 17:01 UTC, sh0ji commented on packages/react/src/components/StepIndicator/index.stories.tsx
> +interface StepIndicatorControls extends StepIndicatorProps {
Hmm, my first instinct is that it shouldn't live inside `@wwnds/react` source because it's not part of that library, so maybe just export it from `/.storybook` somewhere? That will create some ugly imports, but we could solve that with [TypeScript paths](https://www.typescriptlang.org/tsconfig#paths) (e.g., `import { whatever } from '@nds-storybook-utils'` or something like that).

All that said, I'd be okay with just setting a `const` in this story and then revisiting this later if you'd rather do that.

2022-03-29 17:15 UTC, JRebella commented on packages/react/src/components/StepIndicator/index.stories.tsx
> +interface StepIndicatorControls extends StepIndicatorProps {
By the way, I also just found out there's an option to group controls together like so
![image](https://user-images.githubusercontent.com/47323512/160668391-76d91e54-eafb-4560-a6e3-3abcbdec269c.png)

2022-03-29 18:05 UTC, sh0ji commented on packages/react/src/components/StepIndicator/index.stories.tsx
> +interface StepIndicatorControls extends StepIndicatorProps {
Oh perfect! In that case, let's just put story controls together and then either leave out the description or use it to describe what the control does.

2022-04-04 19:47 UTC, sh0ji requested changes
Looks like your update broke the test. I suggested a fix.

2022-04-04 19:47 UTC, sh0ji commented on packages/react/src/components/StepIndicator/Step.tsx
> +					{completionStatusLabel}
This will render as `<span>completed</span>The label of the step`, which is missing a space between the completion status and the children. I'm not sure if screen readers read it any differently, but it's probably best to add the space.

2022-04-04 19:47 UTC, sh0ji commented on packages/react/src/components/StepIndicator/index.test.tsx
> +	const currentStep = screen.getByRole('listitem', { current: 'step' });
This is failing because you want to use [ByText](https://testing-library.com/docs/queries/bytext/), not [ByLabelText](https://testing-library.com/docs/queries/bylabeltext/) since the span isn't labeling anything&mdash;it's just text.

Also, related to my other comment, this step's [`.textContent`](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) should be `"completedStep 2"`. You can probably check that by logging it in your test: `t.log(currentStep.textContent)`. This is something I do while writing tests to see what's rendering before choosing what assertion to use.

For instance, `t.true(currentStep.textContent.startsWith('completed'))` would be good if we specifically wanted "completed" to always come first. But I don't think we care about order here, and the `within()` assertion doesn't either, so I might just stick with that. It would allow us to move the completion status to after the `children` and still have the test pass.

2022-04-05 14:53 UTC, merged