INDS-162 - Step indicator tests
wwnorton/design-system pull request #268
Opened 2022-03-29 18:21 UTC by JRebella

2022-03-29 21:18 UTC, sh0ji requested changes
Good stuff! I made a couple little tips, most notably the one about how to select for ARIA states with Testing Library.

2022-03-29 21:18 UTC, sh0ji commented on packages/react/src/components/StepIndicator/index.test.tsx
> +	t.is(secondStep.getAttribute('aria-current'), 'step');
Testing library has good support for ARIA properties as selector properties like [`{ current: true }`](https://testing-library.com/docs/queries/byrole/#current), so let's use that here. There are a number of ways you could to this, but here's an example:

```ts
t.is(screen.queryByRole('listitem', { current: 'true' }), secondStep);
```

The advantage of this (and one of the reasons I really like Testing Library) is that `screen.queryByRole('listitem', { current: 'true' })` essentially asserts that a current list item exists without needing to care about implementation (`aria-current="true"` is technically an implementation detail). As far as I know, `aria-current="true"` is the only way to convey the "current" state, but many other states can be implemented in a number of equally valid ways.

For instance, `screen.queryByRole('checkbox', { checked: true })` would find `<input type="checkbox" checked />` but it would also find `<span role="checkbox" aria-checked="true" />` because both are valid implementations for communicating the "checked" state.

2022-03-29 21:18 UTC, sh0ji commented on packages/react/src/components/StepIndicator/index.test.tsx
> +	t.is(secondStep.getAttribute('aria-current'), 'step');
@Apatil15, @wguevara-norton: you two should take note of this too.

2022-03-30 15:34 UTC, JRebella commented on packages/react/src/components/StepIndicator/index.test.tsx
> +	t.is(secondStep.getAttribute('aria-current'), 'step');
That's great, I simplified the tests quite a bit using these query selectors

2022-03-31 14:19 UTC, sh0ji approved these changes
These tests are quite clean! I didn't know about the [within](https://testing-library.com/docs/dom-testing-library/api-within/) utility. :ship:

2022-03-31 14:19 UTC, merged