Loading component with the name progress progressindicator
wwnorton/design-system pull request #54
Opened 2020-12-16 03:29 UTC by Apatil15

Created loading component with the name progressIndicator,Please review and let me know your comments so I can fix according to your reviews. 

Following new folders and files has been added 

1. packages->react->src->components
    - BaseProgressIndicator-> index.tsx //base component
    - ProgressIndicator-> index.tsx //storybook component

2.  packages->core->src->components
    - progressindicator->index.scss

Changes are in existing files
1. cspell.json
2. packages->core->src->index.scss
3. packages->core->src->main.scss
4. packages->react->src->index.ts

Unit testing is pending is I am working on it.

2020-12-18 14:57 UTC, sh0ji requested changes
This is great, thanks for submitting it! I made a lot of comments and some change requests.

Some additional meta comments:

* I like the higher order component approach a lot but since the `label` is effectively required, I'm not sure it's fully necessary here.
* Names: I think the `BaseProgressIndicator` is good but the top-level components might need to be named in line with our designs. Possibly `Spinner` for the circle indicator...

2020-12-18 14:57 UTC, sh0ji commented on packages/react/src/components/ProgressIndicator/index.tsx
> +	color?: Exclude<AllColors, 'disabled'>;
We want this prop to be an abstraction for the design system color system, which means this prop needs to be converted to its CSS custom property. Right now, passing "red" results in the CSS `color: red;` but we want it to result in `color: var(--nds-red-60);`. I think we can go with the `60` grade by default but maybe you could also expose that as a prop (`colorGrade`).

2020-12-18 14:57 UTC, sh0ji commented on packages/react/src/components/ProgressIndicator/index.tsx
> +	return renderElement(baseElement, props, progressIndicator as HTMLElement);
Be very careful about using type assertions (the "as" syntax) like this. You can use them to avoid errors like this but often the error is something you need to account for. In this case, the `ref` parameter of the `renderElement` has the wrong type (see my comment above).

2020-12-18 14:57 UTC, sh0ji commented on packages/react/src/components/ProgressIndicator/index.tsx
> +const renderElement = (refElement: JSX.Element, props: BaseIndicatorProps, ref: HTMLElement) => {
`ref` can be `null`: `ref: HTMLElement | null`.

2020-12-18 14:57 UTC, sh0ji commented on packages/core/src/components/progressindicator/index.scss
> +	span {
Is there a BEM name we can give this rather than styling a span directly?

2020-12-18 14:57 UTC, sh0ji commented on packages/react/src/components/ProgressIndicator/index.tsx
> +	const labelElement = <span>{props.label}</span>;
The label needs to be used as the [accessible name](https://w3c.github.io/accname/#dfn-accessible-name) for the progress indicator (the thing with `role="progress"`). There are two ways that I could imagine doing that here:

1. Set the `aria-label` on the element with `role="progress"` (in other words, `<BaseProgressIndicator aria-label={label} />`)
2. Set `aria-labelledby={ID_OF_LABEL_ELEMENT}` on the element with `role="progress"` and set `id={ID_OF_LABEL_ELEMENT}` on this span.

In this case, option 1 makes more sense to me since it doesn't require you to generate a unique id.

2020-12-18 14:57 UTC, sh0ji commented on packages/react/src/components/ProgressIndicator/index.tsx
> +		<div className={`${prefix('progressindicator')} nds-${props.labelPosition ? props.labelPosition : 'bottom'}`}>
I think this should be a `span` since it's (correctly) `display: inline-flex`.

2020-12-18 14:57 UTC, sh0ji commented on packages/core/src/components/progressindicator/index.scss
> +		margin-left: 10px;
Margins and paddings should always use our [spacing system](https://github.com/wwnorton/design-system/tree/main/packages/core/src/spacing) and it looks like [the Zeplin design for this](https://app.zeplin.io/project/5d66e28439bbe3139aa846ad/screen/5efb625f296fcc9f51c1f1a7) uses `0.5rem`, which you can set with our [spacer function](https://github.com/wwnorton/design-system/blob/68bfc7601271aa00fe940e858f54ff592a778717/packages/core/src/spacing/index.scss#L118-L121) like this:

```scss
margin-left: nds.spacer('inline-x-sm');
```

2020-12-18 14:57 UTC, sh0ji commented on packages/core/src/components/progressindicator/index.scss
> +		.nds-top {
These positioning classes are going to result in CSS that will affect _any_ element with `class="nds-top"`, which may or may not be okay. If that's something we want, it might make sense to pull it out into a more generic "positioning" set of utility classes but I'm inclined to just make it more specific here.

That can be done by either using the `--modifier` BEM convention (`.nds-progressindicator--label-top`) or mimicking [our tooltip's placement convention](https://github.com/wwnorton/design-system/blob/68bfc7601271aa00fe940e858f54ff592a778717/packages/core/src/components/tooltip/index.scss#L110-L128), which itself comes from [Popper.js](https://popper.js.org/).

2020-12-18 14:57 UTC, sh0ji commented on packages/core/src/components/progressindicator/index.scss
> +@mixin top {
Just using the position makes these positioning mixins a bit ambiguous&mdash;is the `label` being set `top` or is the progress indicator/spinner? The same goes for the class declarations (`.nds-top` vs `.nds-progressindicator--label-top`).

Since the React prop for this is `labelPosition`/`labelPlacement`, lets make these `labelTop`/`labelBottom`/etc.

2020-12-18 14:57 UTC, sh0ji commented on packages/core/src/components/progressindicator/index.scss
> +	flex-direction: column-reverse;
Changing order with CSS only affects the visual layout, but there are three other layouts that always follow DOM order:

- selection - if you've ever tried to select two adjacent blocks of text and the order is off, you know how infuriating this can be. I don't think we need to worry about this but I don't want to assume that.
- focus - aka the <kbd>Tab</kbd> order. Nothing here is focusable so I think this is unaffected here.
- screen readers (assistive tech in general) - the most common way to navigate with a screen reader is by arrowing, which moves linearly through DOM elements.

I think we can leave this in for now but I'll want to do some testing on this to make sure it's not breaking any of the other layouts.

2020-12-18 14:57 UTC, sh0ji commented on package.json
> +    "sass-loader": "^10.1.0"
What's this doing here?

2020-12-23 14:37 UTC, Apatil15 commented on packages/react/src/components/BaseProgressIndicator/index.tsx
> +export interface BaseProgressIndicatorProps extends React.DetailsHTMLAttributes<HTMLElement> {
- Rename top level component ProgressIndicator to Spinner.  
- Inherited props from CircularProgress  component
- Changed interface to type

2020-12-23 14:38 UTC, Apatil15 commented on packages/react/src/components/BaseProgressIndicator/index.tsx
> +	progressValue?:number;
Read properties from CircularProgress and used name value instead of progressValue

2020-12-23 14:40 UTC, Apatil15 commented on packages/react/src/components/BaseProgressIndicator/index.tsx
> +	ariaBusy?:boolean,
Removed aria-busy and aria-describedby.

2020-12-23 14:50 UTC, Apatil15 commented on packages/react/src/components/BaseProgressIndicator/index.tsx
> +	...props
Removed ...props and added only those properties which are using 
{
	thickness,
	value,
	variant,
	color,
}

2020-12-23 14:51 UTC, Apatil15 commented on packages/react/src/components/BaseProgressIndicator/index.tsx
> +			aria-label="progressbar"
Removed

2020-12-23 14:52 UTC, Apatil15 commented on packages/react/src/components/ProgressIndicator/index.tsx
> +	labelPosition?: LabelPosition | 'bottom'
Changed labelPosition to LablePlacement

2020-12-23 14:53 UTC, Apatil15 commented on packages/react/src/components/ProgressIndicator/index.tsx
> +export interface BaseIndicatorProps extends BaseProgressIndicatorProps {
Removed repeated property declaration

2020-12-23 14:54 UTC, Apatil15 commented on packages/react/src/components/ProgressIndicator/index.tsx
> +	color?: Exclude<AllColors, 'disabled'>;
I added in base component and working as expected but need your suggestion.

const circularColor = color ? `var(--nds-${color}-60)` : color;

2020-12-23 14:56 UTC, Apatil15 commented on packages/react/src/components/ProgressIndicator/index.tsx
> +	return renderElement(baseElement, props, progressIndicator as HTMLElement);
Removed code for reference element and changed renderElement function implementation

2020-12-23 14:58 UTC, Apatil15 commented on packages/core/src/components/progressindicator/index.scss
> +		margin-left: 10px;
Changed css property implementation read margin from spacing.rem(0.5); as per the Zaplin

2020-12-23 14:59 UTC, Apatil15 commented on packages/core/src/components/progressindicator/index.scss
> +@mixin top {
Used spinner-placement- for each of the class name for unique identification

2020-12-23 15:00 UTC, Apatil15 commented on package.json
> +    "sass-loader": "^10.1.0"
Removed sass-loader, solved problem after ran npm run bootstrap

2021-01-04 15:33 UTC, sh0ji commented on packages/react/src/components/BaseProgressIndicator/index.tsx
> +	...props
You still need to pull out the remaining properties with `...props` and then apply it to the `CircularProgress`, otherwise we won't be able to pass props inherited by the `React.HTMLAttributes<HTMLSpanElement>` interface.

2021-02-03 22:50 UTC, sh0ji commented
Let's add [Progress Bar](https://zpl.io/V08QAQo) to this, using [Material's linear progress](https://material.io/components/progress-indicators#linear-progress-indicators) as our model for styling but adapted to NDS.

2021-02-12 22:15 UTC, Apatil15 commented
Update spinner review changes with progress bar component so closing this.

2021-02-12 22:15 UTC, closed without merging