Callout
wwnorton/design-system pull request #69
Opened 2021-01-31 23:10 UTC by ParmeJon

- adds Callout, CalloutSuccess, CalloutWarning, CalloutError component
- adds Callout scss styling
- adds warning svg

WIP
- need to add dynamic hover color for close button
- need to incorporate `backgroundColor` and `borderColor` props API.

2021-02-04 18:33 UTC, sh0ji requested changes
This is great, I'm excited to get your first PR in the design system! :sparkles: 

I was very comprehensive since this is your first PR. Most of my change requests should be pretty clear and should help you simplify things but let me know if you have any questions.

One high-level tip that's only kind of captured in the review is to try your best to replicate the component's anatomy in its composition in CSS and React. In other words, if the anatomy has a 3 parts, your component's render function should strive to have 3 parts as well. This isn't technically required but helps connect the dots between the specification and the implementation. That will help readability of the code and keep the API as simple as possible.

2021-02-04 18:33 UTC, sh0ji commented on packages/core/src/components/callout/index.scss
> +	transform: translate(18%, -18%);
I like this use of `transform` to position this but wonder if using tokens would be a more accurate & semantic way of doing it. For instance, would this work?

```scss
translate(
	calc(var(--nds-callout-padding-y) - var(--nds-button-padding-y)),
	calc(-1 * (var(--nds-callout-padding-x) - var(--nds-button-padding-x))),
);
```

2021-02-04 18:42 UTC, sh0ji commented on packages/react/src/components/Callout/index.tsx
> +	borderPosition?: BorderPositionType,
Actually, disregard the request to change it to "placement." After thinking about it, I think we should use "placement" more narrowly to describe how things are placed adjacent to things and borders don't do that.

The second point about setting the type directly is still valid so I'll leave this unresolved.

2021-02-04 18:46 UTC, sh0ji commented on packages/core/src/components/callout/index.scss
> +@mixin title {
Oh you know what, could you use a [heading typeset](https://wwnorton.github.io/design-system/sassdoc/#typography-mixin-typeset-heading) for this?

```scss
@mixin title {
	@include heading-4;
}
```

2021-02-04 18:50 UTC, sh0ji commented on packages/react/src/components/Callout/CalloutError.tsx
> +export type CalloutErrorProps = Omit<CalloutProps, 'borderPosition' | 'icon' | 'iconColor' | 'color'>;
Let's export one `CalloutPresetProps` type from the `index.tsx`, which you can then use in each of the presets rather than recreating it in each preset.

2021-02-04 21:38 UTC, ParmeJon commented on .cspell.json
> +    "dismissable",
Whoops! For some reason I was so sure that was how you spelled it, even with CSpell yelling at me, haha. I have changed this in my latest commits.

2021-02-04 21:40 UTC, ParmeJon commented on packages/react/src/components/Callout/index.tsx
> +			{ !title && !icon && !dismissable ? null : (
This makes sense. I opted for the first option and memoized the condition like you had it.

2021-02-04 21:44 UTC, ParmeJon commented on packages/core/src/components/callout/index.scss
> +		background-color: var(--nds-callout-color-20);
This does indeed work. It makes things a bit more dynamic as well; I have made some changes for this.

2021-02-04 22:54 UTC, sh0ji commented on .cspell.json
> +    "dismissable",
Trust in the linter gods!

2021-02-05 18:01 UTC, ParmeJon commented on packages/core/src/components/callout/index.scss
> +
I assume you meant "callout-body"? Gotcha though, makes sense in order for us to keep our callout padding look.

2021-02-05 22:21 UTC, ParmeJon commented on packages/core/src/components/callout/index.scss
> +	min-height: 1.375rem;
Whenever there isn't an icon and title the header element height becomes 0. This throws off the positioning for close-button which is set to `position: absolute` in relation to the header element.
 
To remedy this I used a min-height for the header to maintain the spacing between the border, close-button and callout-body.

Might be alternatives?

2021-02-05 22:50 UTC, ParmeJon commented on packages/core/src/components/callout/index.scss
> +@mixin title {
I added the changes we discussed to typeset-heading mixin.
```scss
@mixin typeset-heading($size, $height) {
	margin-top: 0;
	margin-bottom: spacing.spacer('block-base');
	font-style: var(--nds-font-style-headings);

	@include typeset(
		$size: $size,
		$height: $height,
		$family: var(--nds-font-family-headings),
		$weight: var(--nds-font-weight-headings),
	);

        // added this
	&:last-child {
		margin-bottom: unset;
	}
}
```

One minor issue with this is that I originally had the `close-button` as the last element in the header element. This would make it so the margin-bottom is still applied since `close-button` is the last element. Since `close-button`'s position is absolute I moved the element to the top of header like this so that the title div was the last-child:.

```jsx
<header>
 <Button variant='ghost' icon='close'>Close </Button>
 <BaseIcon /> 
 <div className={headerTitleClass}></div>

</header>
```

Does this cause any issues semantically? With close-button visually appearing later but appearing earlier in the HTML?

2021-02-05 22:56 UTC, ParmeJon commented on packages/core/src/components/callout/index.scss
> +@mixin title {
Also changing the order of the `header` elements will require changes to the way I'm handling adding padding to the title `div` based on if the close-button exists or not (which was assumed to be the last-child).

2021-02-08 15:58 UTC, sh0ji commented on packages/core/src/components/callout/index.scss
> +@mixin title {
Ah yeah, that's a good point. Let's just revert that change to `typeset-heading` and revisit it later. For the time being, you can set the title manually like you had it originally or use the `typeset` mixin, which doesn't include any margin.

Sorry for the back and forth!

2021-02-11 23:41 UTC, sh0ji commented
@ParmeJon, I'm going to merge this but I wanted to recommend that you read through my commits a bit since I made some small and some not-so-small changes.

Thanks for all your work on this, your first component in the design system! :tada: :beers:

2021-02-11 23:41 UTC, sh0ji approved these changes

2021-02-11 23:42 UTC, merged