feat: add menu component
wwnorton/design-system pull request #79
Opened 2021-02-11 01:33 UTC by Apatil15

Added new menu component with the supportive following components.

1. Menu
2. MenuItem
3. MenuDivider
4. MenuHeader
5. MenuGroup

Created folders according to menu component.
1. _react/src/components/BaseMenu/_
2. _react/src/components/Menu/_

Also created following style file and token
_core/src/components/menu/index.scss_ 
_/core/src/components/menu/tokens.scss_

Taking care design menu as per the discussion. 
 
Following features has been added

1. Menu item hover color.
2. Menu item focus color.
3. Menu item selected color.
4. On menu item click get all the selected properties.
5. Auto hide when click on external element.
6. Set element position as per the parent element.
7. Set default focus.
8. Dynamic json menu generation.
9. Menu item click event
10.Menu item url redirect

@sh0ji Please review code and let me know your review comments.

2021-02-11 23:15 UTC, sh0ji requested changes
Thanks for this, @Apatil15! This is probably our most complex component yet so I appreciate everything that went into it.

I haven't reviewed everything in its entirety but I see some things that are probably best addressed now rather than being comprehensive.

1. `Base` components should really only handle polyfilling behavior and setting the unstyled semantics of a pattern. In other words, they should mostly just inherit an HTML interface as their props and default props should only ever be used for polyfilling. This effectively means that some of your code in the `Base` components needs to be pulled up to the non-`Base` ones.
   - I outlined what I think `BaseMenuGroup` should do in a code comment so you can see what I mean.
2. Menus cannot be used to select items. That's what a [listbox](https://w3c.github.io/aria/#listbox) is used for (and it's what our `BaseListbox` + `BaseOption` accomplishes).
   - The exception to this might be a `menuitemcheckbox` or `menuitemradio` but those are out of scope for this initial PR.
3. It occurs to me that we'll need a `Link` or `Anchor` component to address the issue of router-provided links. I'll open a separate issue for that (it's long been neglected).

2021-02-14 02:12 UTC, Apatil15 commented on packages/react/src/components/BaseMenu/baseMenuDivider.tsx
> +	...props
Resolved as per the comments

2021-02-14 02:13 UTC, Apatil15 commented on packages/react/src/components/BaseMenu/baseMenuDivider.tsx
> +		className='nds-menu-divider'
Style applied as per the role

2021-02-14 02:13 UTC, Apatil15 commented on packages/react/src/components/BaseMenu/baseMenuGroup.tsx
> +export const BaseMenuGroup = React.forwardRef<HTMLLIElement, BaseMenuGroupProps>(({
Code has been update

2021-02-17 14:37 UTC, Apatil15 commented on packages/react/src/components/BaseMenu/baseMenuDivider.tsx
> +		className='nds-menu-divider'
Created new menuButton component and inherited from button component

2021-04-01 20:41 UTC, sh0ji commented
We'll address this in another PR.

2021-04-01 20:41 UTC, closed without merging